//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desafioProg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class desafioProgEntities : DbContext
    {
        public desafioProgEntities()
            : base("name=desafioProgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cafes> cafes { get; set; }
        public virtual DbSet<etapas> etapas { get; set; }
        public virtual DbSet<participante> participante { get; set; }
        public virtual DbSet<salas> salas { get; set; }
    }
}
