//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desafioProg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participante
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public int sala1 { get; set; }
        public int sala2 { get; set; }
        public int cafe1 { get; set; }
        public int cafe2 { get; set; }
    
        public virtual cafes cafes { get; set; }
        public virtual cafes cafes1 { get; set; }
        public virtual salas salas { get; set; }
        public virtual salas salas1 { get; set; }
    }
}
